### ISSUE TITLE
Balance of Spells

### ISSUE THREAD

**Issue by Elobomg** [Stereowalker/C.O.M.B.A.T#51]
So I I was touching a bit of the config files, im planning to use this mod with scaling health mod but the spell system feels a bit weird or maybe im not understanding it correctly.

First I level up to 32 the magic strenght atribute, which I configurate to get 80 magic damage at max level, the difficulty level right now is 1300, which makes mob to get from 1300 up to 3600 HP. I can oneshot anything with the Lighting bot spell in a master shulker wand but varely do 30 or so damage with any other lighting skill, also tried Black hole and it can do a little bit more of damage but not near the oneshot of the lighting bolt. Also tried with water and fire bolts.

Maybe adding a way to configurate the spells?

**Comment by Stereowalker** [comment]
I never really considered that anyone would do that. For now, black hole scales according to your magic strength. The lightning spells won't scale because I'm using vanilla lightning, but in the 1.16.x update of the mod, Lightning should also scale to the users magic strength. Thanks for pointing this out to me
