### ISSUE TITLE
About mods.toml

### ISSUE THREAD

**Issue by VulpesStella** [Stereowalker/C.O.M.B.A.T#85]
Noticed that in version"1.16.5-7.2.1"
JEI was set to be a mandatory dependency while CuriosAPI was a non-mandatory one  0.0
I wonder if this above was a mistake, or, a new change?

**Comment by Stereowalker** [comment]
The mod adds custom workbenches with each having its own recipes. Making JEI mandatory will prevent a lot of players from asking me how certain items are crafted since they should have JEI installed. Curios is optional because UnionLib already has an inventory system much like baubles. The mod only supports curios because it's popular and in the case where it is installed will use the curios inventory system instead. This mod should work as intended even without curios installed
